language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:

  # TODO: remove when we stop testing against node 6
  - if [[ `npm -v` < 6* ]]; then npm i -g npm@6; fi

  - npm install -g bower
  - bower --version
